## compose 파일 버전
#version: '3'
#services:
#  # 서비스 명
#  kafka-ui:
#    # 사용할 이미지
#    image: provectuslabs/kafka-ui
#    # 컨테이너명 설정
#    container_name: kafka-ui
#    # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
#    ports:
#      - "8081:8080"
#    # 환경 변수 설정
#    environment:
#      - KAFKA_CLUSTERS_0_NAME = local
#      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS = kafka:29092
#      - KAFKA_CLUSTERS_0_ZOOKEEPER = zookeeper:2181


version: '2'
services:
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8989:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-1:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper-1:32181