#version: '2'
#services:
#  kafka:
#    image: confluentinc/cp-kafka:5.5.1
#    container_name: kafka-msa
#    ports:
#      - "9092:9092"
#    environment:
#      - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
#      - KAFKA_ADVERTISED_PORT=9092
#      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
#      - KAFKA_INTER_BROKER_LISTENER_NAME= INTERNAL
#      - KAFKA_ADVERTISED_LISTENERS= INTERNAL://kafka:29092,EXTERNAL://localhost:9092
#    depends_on:
#      - zookeeper
#  zookeeper:
#    image: confluentinc/cp-zookeeper:5.5.1
#    ports:
#      - "2181:2181"
#    environment:
#      - KAFKA_ADVERTISED_HOST_NAME=zookeeper

version: '3.8'
services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - '32181:32181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000


  kafka-1:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-msa
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper-1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-1:32181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:29092,EXTERNAL://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
#      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
#      KAFKA_NUM_PARTITIONS: 3


#  kafka-2:
#    image: confluentinc/cp-kafka:5.5.1
#    ports:
#      - '9093:9093'
#    depends_on:
#      - zookeeper-1
#    environment:
#      KAFKA_BROKER_ID: 2
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:32181
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
#      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-2:29093,EXTERNAL://localhost:9093
#      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
#      KAFKA_NUM_PARTITIONS: 3
#
#
#  kafka-3:
#    image: confluentinc/cp-kafka:5.5.1
#    ports:
#      - '9094:9094'
#    depends_on:
#      - zookeeper-1
#    environment:
#      KAFKA_BROKER_ID: 3
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:32181
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
#      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-3:29094,EXTERNAL://localhost:9094
#      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
#      KAFKA_NUM_PARTITIONS: 3